const data = {
  msg: '操作成功',
  code: 0,
  data: {
    pageNow: 1,
    pageSize: 10,
    totalPage: 3,
    totalCount: 10,
    datas: [
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
      {
        id: 10,
        name: 'Activewear',
        years: 4,
        logo: 'https://cdn.image.kfbuy.com/EC50A043-13B1-4fb3-9EF7-55F461D8E530.png',
        imgUrl: 'https://cdn.image.kfbuy.com/banner_10.jpg',
        description: "Our business line covers women t-shirts and men's T-shirt, ladies blouses and tops, woman casual dress, fashion dresses, maxi and long dresses such as evening dresses, cocktail party dress, female and male hoodies and sweatshirts, all season short coats, long autumn and winter coats or jackets , Fall sweaters, mini / short / maxi skirts, pants and trousers, jeans, sporting suits, sporting pants and leggings, tank tops / vests, etc.",
      },
    ],
  },
};

export default data;
